package com.clara.ops.challenge.document_management_service_challenge.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

/**
 * JPA entity representing a PDF document stored in the system. Metadata is persisted in the
 * {@code document_schema.documents} table; the associated tags are stored in a separate
 * {@code document_schema.document_tags} table via an {@link ElementCollection}.
 *
 * <p>A unique constraint on {@code (username, fileName)} prevents duplicate uploads for the same user,
 * providing database-level idempotency as a final safeguard.
 */
@Entity
@Table(
        name = "documents",
        schema = "document_schema",
        uniqueConstraints = @UniqueConstraint(
                name = "uk_documents_username_file_name",
                columnNames = {"username", "file_name"}))
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Document {

    /** Unique identifier generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /**
     * The username that owns this document. Stored as {@code username} to avoid conflict with the SQL
     * reserved word {@code user}.
     */
    @Column(name = "username", nullable = false)
    private String user;

    /** Human-readable fileName of the document (used as the file fileName in object storage). */
    @Column(name = "file_name", nullable = false)
    private String fileName;

    /**
     * Free-form tags associated with the document. Each tag is persisted as an individual row in the
     * {@code document_tags} table, enabling efficient indexed lookups.
     */
    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(
            name = "document_tags",
            schema = "document_schema",
            joinColumns = @JoinColumn(name = "document_id"))
    @Column(name = "tag")
    @Builder.Default
    private List<String> tags = new ArrayList<>();

    /** Fully-qualified object path within the storage bucket (e.g. {@code user1/report.pdf}). */
    @Column(name = "storage_path", nullable = false)
    private String storagePath;

    /** Size of the uploaded file in bytes. */
    @Column(name = "file_size", nullable = false)
    private Long fileSize;

    /** MIME type of the uploaded file (e.g. {@code application/pdf}). */
    @Column(name = "file_type", nullable = false)
    private String fileType;

    /** Timestamp at which the record was created; set automatically by Hibernate on insert. */
    @Column(name = "created_at", nullable = false, updatable = false)
    @CreationTimestamp
    private LocalDateTime createdAt;
}